version: "3.9"
services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    container_name: hydra
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hydra
