version: "3.9"
services:
  database:
    image: postgres:latest
    container_name: hydra-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hydra
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: hydra-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/Documents/data/rabbitmq/data/:/var/lib/rabbitmq
      - ~/Documents/data/rabbitmq/log/:/var/log/rabbitmq
